services:
  backend-spring:
    container_name: backend-spring
    image: docker.io/dorra12/tpfoyer-app:latest
    build:
      context: .
      args:
        NEXUS_USER: "admin"
        NEXUS_PASSWORD: "admin"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tpFoyer17?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""

      MYSQL_ROOT_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8082:8082"
    depends_on:
      - db
    restart: on-failure


  db:
    container_name: db
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: tpFoyer17
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql





volumes:
  mysql-data:
